name: Run Tests and Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prompt-manager
    steps:
      - name: Checkout to working branch
        uses: actions/checkout@v4

      - name: actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 23.10.0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run:
         - cd prompt-manager
         - pnpm install

      - name: Run Jest tests
        run: pnpm test

  build_dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prompt-manager
    steps:
      - name: Checkout to working branch
        uses: actions/checkout@v4

      - name: actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 23.10.0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build in dev mode
        run: pnpm build dev
